### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [bertdida/DeclareThatColor#10]
Hi @bertdida I am tobaloidee again, I designed your logo for TwitterQuoteScraper. I would like to do a logo also for this project of yours..If you are interested I will work again. Thanks!

**Comment by bertdida** [comment]
Sure! I'm very pleased for your another logo proposal. Anytime you're ready @Tobaloidee . :)

**Comment by Tobaloidee** [comment]
Will start designing and show it here when done.. 👍

**Comment by Tobaloidee** [comment]
Here's what I came up with @bertdida  I hope you like it!

- I researched some color logos & there are so many already and I don't want to create a generic design that is why I went on the initials of your project which is D-T-C for DeclareThatColor. I combined those three initials to form a compact logomark with the actual colors in the middle. I made it look italicized for a more active and strong logo.

![declarethatcolor-01](https://user-images.githubusercontent.com/36028424/56980569-473ade80-6baf-11e9-8074-6166598cc3e3.png)

If you liked it and doesn't have any suggestions, I will finalize the files already and make a PR. 
😊

**Comment by bertdida** [comment]
This is cool @Tobaloidee, i like this. One suggestion though, can we make it a little tighter/compressed? I can't immediately notice the letters D and C, because of the color bar taking lots of attention.

![image](https://user-images.githubusercontent.com/38489033/57052086-93714600-6cb7-11e9-8c50-cb79d550b060.png)

**Comment by Tobaloidee** [comment]
here @bertdida  I made some adjustments. cleaner version

![Untitled-1-01](https://user-images.githubusercontent.com/36028424/57053959-3039e080-6cc4-11e9-811f-ff56e5a85d34.png)

**Comment by bertdida** [comment]
I see. But I'll go with the first one. :)

You may now finalize the files and create a PR 😊

**Comment by Tobaloidee** [comment]
Okidoki! 👍😊

**Comment by Tobaloidee** [comment]
Here's the PR #11 for the logo upload and readme update @bertdida .

-You can download all the versions and files of your new logo [HERE](https://drive.google.com/drive/u/1/folders/1A23jzOsw3jFCPlM1KD00fSKq_k8IwRzW)

Thanks again!

**Comment by bertdida** [comment]
PR merged. thanks @Tobaloidee  :)

**Comment by bertdida** [comment]
I'll edit README to include you on credits.

**Comment by Tobaloidee** [comment]
Okidoki!! Thanks again!😀
